apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-web-api
  name: sample-web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-web-api
  template:
    metadata:
      labels:
        app: sample-web-api
    spec:
      containers:
      - image: harbor.derrickwong.hk/apps/sample-web-api:latest
        name: sample-web-api
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-web-api
  name: sample-web-api
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: sample-web-api
  type: LoadBalancer
